### ISSUE TITLE
Map/tile base high address specificatons in layer 0/1 registers seem incorrect

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-docs#21]
Shouldn't (17:10) in the layer 0/1 register specifications in the VERA Programmer's Reference illustrated below be (16:10) since the Video RAM address range is $00000 - $1FFFF?

3 | Ln_MAP_BASE_H | MAP_BASE (17:10)

5 | Ln_TILE_BASE_H | TILE_BASE (17:10)

**Comment by indigodarkwolf** [comment]
I suspect this bit specification owes some legacy to when the VERA included PETSCII font data in a portion of ROM located at $20000 (see the [Vera 0.7 specifications](https://github.com/commanderx16/x16-docs/blob/master/old/vera-module%20v0.7.pdf) for the historical context).

Seems like a worthy question for @fvdhoef. Does the VERA still use bit 17 in these fields? Should the docs be changed to 16:10 to reflect the current valid memory range? 

What happens if VERA attempts to access VRAM in the $20000 neighborhood, anyways? Garbage? 0's? Wrap-around to values starting from $00000?

**Comment by mist64** [comment]
I've updated the documentation to 17 bits (0-16). The behavior of the 17th bit is undocumented and should not be relied upon. :)
