### ISSUE TITLE
Registers Addresses are Wrong

### ISSUE THREAD

**Issue by oziphantom** [commanderx16/x16-docs#50]
$9F2A | DC_HSCALE (DCSEL=0) | Active Display H-Scale
-- | -- | --
$9F2B | DC_VSCALE (DCSEL=0) | Active Display V-Scale
$9F2C | DC_BORDER (DCSEL=0) | Border Color
$9F29 | DC_HSTART (DCSEL=1) | Active Display H-Start (9:2)
$9F2A | DC_HSTOP (DCSEL=1) | Active Display H-Stop (9:2)
$9F2B | DC_VSTART (DCSEL=1) | Active Display V-Start (8:1)
$9F2C | DC_VSTOP (DCSEL=1) | Active Display V-Stop (8:1)

not how it get to 2C then go back to 29 and keeps counting so every registers after DC_BORDER is wrong.

**Comment by indigodarkwolf** [comment]
You misunderstand.

The registers are correct, their behavior depends on the value of DCSEL in $9F25.

When DCSEL is 0, the registers are as follows:

|Register|Name|Description|
|-|-|-|
|$9F29|DC_VIDEO (DCSEL=0)|Various bits as described in the documentation|
|$9F2A|DC_HSCALE (DCSEL=0)|Active Display H-Scale|
|$9F2B|DC_VSCALE (DCSEL=0)|Active Display V-Scale|
|$9F2C|DC_BORDER (DCSEL=0)|Border Color|

But when DCSEL is 1, the registers change as follows:
|Register|Name|Description|
|-|-|-|
|$9F29|DC_HSTART (DCSEL=1)|Active Display H-Start (9:2)|
|$9F2A|DC_HSTOP (DCSEL=1)|Active Display H-Stop (9:2)|
|$9F2B|DC_HSTART (DCSEL=1)|Active Display V-Start (8:1)|
|$9F2C|DC_HSTART (DCSEL=1)|Active Display V-Stop (8:1)|

This is what "(DCSEL=0)" and "(DCSEL=1)" are trying to convey, without adding additional complex structures to the table layout. As it stands, the table is already more complicated than Markup can express, which is why it's defined in HTML.

**Comment by oziphantom** [comment]
Yep my bad.
